== Introduction

Data from biodiversity baseline assessment and monitoring plays a crucial role in understanding current and potential future impacts of development on the natural environment, whether these impacts are from industrial, infrastructure, agricultural, extractive or other projects. Data about the occurrence of species in space and time are needed to underpin efforts to avoid, mitigate, restore or offset impacts on biodiversity through the Mitigation Hierarchy. Effective decision-making in this area is also crucial for aligning with international best practices and fulfilling international commitments under the https://sustainabledevelopment.un.org/[UN Sustainable Development Goals] and the https://www.cbd.int/[Convention on Biological Diversity].

Gathering biodiversity data is one of the most expensive and time-consuming components of the impact assessment process. During field surveys, experts must account for the range of species and habitats, as well as migratory patterns and life cycles of species across seasons. While aligning data collection periods with project and financing life cycles can be a challenge, failure to plan repeat visits across different seasons can lead to project delays, additional costs and failure to understand differences in likely impacts over time. The scarcity of available resources in developing countries often adds further limitations in the amount of existing data available for EIAs, even in areas known to be biologically rich and diverse.

Despite its potential value beyond any given project, biodiversity assessment and monitoring data are rarely shared. Instead, valuable datasets remain archived within company databases and systems where they fail to yield returns on the significant amounts of time and money already invested in them. 

GBIF—the Global Biodiversity Information Facility—is an international network and research infrastructure that makes biodiversity data freely and openly accessible to scientists, researchers, authorities and citizens anywhere. Its aim is to produce economic and social benefits and enable sustainable development by providing sound scientific evidence on biodiversity. To that end, GBIF and its global community of practice provide a suite of standards, tools and infrastructure to support the management, publication, use and reuse of primary biodiversity data. This guide updates https://www.iaia.org/uploads/pdf/sp7.pdf[Publishing EIA-Related Primary Biodiversity Data: GBIF-IAIA Best Practice Guide] (2011), a joint publication of GBIF and IAIA, offering a current view of how EIA practitioners can make more effective use of these resources.
